name: Acceptance Tests (GKE)

on:
  workflow_dispatch:
    inputs:
      region:
        description: The GKE region
        default: us-east1
      zone:
        description: The GKE zone
        default: us-east1-b
      kubernetesVersion:
        description: The GKE kubernetes version
        default: 1.27
      workersCount:
        description: The number of cluster nodes to provision
        default: 2
      nodeMachineType:
        description: The type of GKE instance to use for cluster nodes
        default: e2-standard-8
      runTests:
        description: The regex passed to the -run option of `go test`
        default: ^TestAcc
      terraformVersion:
        description: Terraform version
        default: 1.5.6

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ github.event.inputs.region }}
  GOOGLE_ZONE: ${{github.event.inputs.zone}}
  USE_GKE_GCLOUD_AUTH_PLUGIN: True
  KUBECONFIG: ${{ github.workspace }}/kubernetes/test-infra/gke/kubeconfig

jobs:
  acceptance_tests:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          access_token_lifetime: "10800s"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ github.event.inputs.terraformVersion }}
          terraform_wrapper: false
      - name: Provision GKE Cluster
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/gke
        env:
          TF_VAR_kubernetes_version: ${{ github.event.inputs.kubernetesVersion }}
          TF_VAR_workers_count: ${{ github.event.inputs.workersCount }}
          TF_VAR_node_machine_type: ${{ github.event.inputs.nodeMachineType }}
        run: |
          terraform init
          terraform apply -auto-approve
      - name: Run Acceptance Test Suite
        env:
          KUBE_CONFIG_PATH: ${{ env.KUBECONFIG }}
          TESTARGS: -run '${{ github.event.inputs.runTests }}'
          # Do not set TF_ACC_TERRAFORM_PATH or TF_ACC_TERRAFORM_VERSION.
          # In this case, the framework will search for the Terraform CLI binary based on the operating system PATH.
          # Eventually, it will use the one we set up.
          # More information: https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests#terraform-cli-installation-behaviors
        run: |
          make testacc
      - name: Destroy GKE cluster
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/gke
        run: |
          terraform destroy --auto-approve
